spring:
  profiles: dev
  datasource:
    username: bibhu04
    url: jdbc:mysql://localhost:3306/student_local_db
    password: bibhu04
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  profiles: qa
  datasource:
    username: bibhu04
    url: jdbc:mysql://localhost:3306/student_local_db_qa
    password: bibhu04
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always

---

spring:
  profiles: prod
  datasource:
    username: bibhu04
    url: jdbc:mysql://localhost:3306/student_local_db_prod
    password: bibhu04
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always

---

spring:
  profiles:
    active: dev
